CREATE SCHEMA IF NOT EXISTS dbo;

INSERT INTO dbo.PRODUTO (PRODUTO_ID, PRODUTO_NOME, PRODUTO_TIPO, PRODUTO_RENTABILIDADE, PRODUTO_RISCO, PRODUTO_LIQUIDEZ)
VALUES (101, 'CDB Caixa 2026', 'CDB', 0.1200, 'Baixo', 2);
